### ISSUE TITLE
Release 1.2.2

### ISSUE THREAD

**Issue by devshorts** [godaddy/godaddy-logger#12]

**Comment by devshorts** [comment]
Maybe lets remove the maven version in the readme and instead link to a maven badge https://github.com/jirutka/maven-badges in the readme, so it dynamically adjusts

**Comment by jakeswenson** [comment]
@devshorts i've changed the readme to use shields.io for its badge and fixed some issues.
https://github.com/godaddy/godaddy-logger/commit/235867b74655ff1c9955abdffa565133ea88c93e

**Comment by devshorts** [comment]
Awesome, thanks @jakeswenson!
