### ISSUE TITLE
LoggingScope annotation doesn't work for read-only fields

### ISSUE THREAD

**Issue by sjlbos** [godaddy/godaddy-logger#16]
**Description**
When using a @LogggingScope annotation on a read-only field (ie. a private field with a getter but no setter) the LoggingScope annotation will be ignored. 

**Example**
Given the following class:
```package com.godaddy.logging.models;

import com.godaddy.logging.LoggingScope;
import com.godaddy.logging.Scope;

public class ExampleClass {

    @LoggingScope(scope = Scope.HASH)
    private String creditCardNumber;

    public ExampleClass(String creditCardNumber) {
        this.creditCardNumber = creditCardNumber;
    }

    public String getCreditCardNumber() {
        return this.creditCardNumber;
    }
}
```

If the class is logged via:
`logger.with(new ExampleClass("MyCreditCardNumber")).info("");`

This will result in the output:
`ExampleClass.creditCardNumber="MyCreditCardNumber"`

**Cause**
This bug appears to be caused by a silent exception being thrown in the "getScopeForMethodField" method of CacheableAccessors.java. When a setter does not exist for the a field, a "java.beans.IntrospectionException" is raised with the message "Method not found: set{field name}". This leads to a short-circuiting of the processing of that field resulting in the default logging scope of "Scope.LOG" being returned.

**Comment by devshorts** [comment]
@bcam909 can you resolve this once we have a new deploy?

**Comment by sjlbos** [comment]
@bcam909 We should close this issue, as it has been fixed.
