### ISSUE TITLE
Hash's default should be cryptographically secure if its intended for personal data.

### ISSUE THREAD

**Issue by jakeswenson** [godaddy/godaddy-logger#4]
I think we should change the default from MD5 to SHA256 if hashing is to be used for sensitive data.

Thoughts? @devshorts @bcam909

**Comment by liujoshua** [comment]
::thumbsup::

**Comment by devshorts** [comment]
:+1:  and easily doable since its already in guava hashing

**Comment by bcam909** [comment]
Addressed in 1.2.1
