### ISSUE TITLE
With syntax for hash processor etc confusing with "withOverride"

### ISSUE THREAD

**Issue by devshorts** [godaddy/godaddy-logger#5]
`withOverride` mutates the current logger adding custom overrides to the current. However, the other `with` statements like `withHashProcessor` and even `useJson` all return a new logger. If the current is not set from the return of that value, then the configs are essentially lost.

I think we should rename "withOverride" to "setOverride" (and leave `withOverride` as deprecated with a note) such that in the future 

`with` = new clone
`set` = mutate current

@jakeswenson @bcam909

**Comment by bcam909** [comment]
It should probably be `addOverride` as we are just adding an entry to the override map. 

I will address this in the next minor release.

:+1:

**Comment by bcam909** [comment]
Addressed in 1.2.1
